<?php
/**
 * @return array[]
 */
function football_league_simulator_theme() {
  return [
    'football_league_overview' => [
      'variables' => [
        'title' => NULL,
        'message' => NULL,
        'teams' => [],
      ],
      'template' => 'football-league-overview',
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function football_league_simulator_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'football_league_simulator/custom_styles';
}

/**
 * @param $variables
 * @return void
 */
function football_league_simulator_preprocess_football_league_overview(&$variables) {
  $query = \Drupal::entityQuery('node')
    ->condition('type', 'team')
    ->accessCheck(TRUE)
    ->execute();

  $teams = \Drupal\node\Entity\Node::loadMultiple($query);

  $teams_data = [];
  foreach ($teams as $team) {
    $teams_data[] = [
      'name' => $team->getTitle(),
      'id' => $team->id(),
      'strength' => $team->field_team_strength->value,
    ];
  }
  $variables['teams'] = $teams_data;
}
